language: ruby
rvm:
  - 2.4.1

addons:
  postgres: "9.4"

script: "cp config/database.yml.sample config/database.yml && bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rspec spec"